---
- name: Apply Java & WebLogic patches
  hosts: all
  gather_facts: no
  roles:
     - role: stopWLS
     - role: patch
       vars:
         domain_name: cebs_app
         old_version: jdk1.8.0_341 
         new_version: jdk1.8.0_361
     - role: patch
       vars:
         domain_name: cebs_app
         old_version: wl12214_220719
         new_version: wl12214_230117
     - role: updateTrustStore
       vars: 
         domain_name: cebs_app
         jdk_version: jdk1.8.0_361
- name: copy NM file
  hosts: all
  gather_facts: no
  tasks:
    - command: mv /opt/home/cebs/NodeManager.sh.1 /opt/home/cebs/NodeManager.sh
      ignore_errors: yes
